language: node_js

os:
  - linux
  - osx
node_js:
  - "7.0"
  - "6.0"
  - "4.0"


sudo: required

addons:
  apt:
    packages:
      - clang-3.3
      - build-essential
      - xvfb
      - gnome-keyring
      - libgnome-keyring-dev
      - libsecret-1-dev

env:
  - CC=clang CXX=clang++ npm_config_clang=1

notifications:
  email: false

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run ./script/cibuild; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm test; fi

git:
  depth: 10
