language: node_js

sudo: false

matrix:
  include:
  - os: osx
  - os: linux
    dist: trusty
    addons:
      apt:
        packages:
        - clang-3.3
        - build-essential
        - libgnome-keyring-dev

addons:
  apt:
    packages:
      - xvfb
      - gnome-keyring
      - libgnome-keyring-dev

env:
  - CC=clang CXX=clang++ npm_config_clang=1

node_js:
  - "7.0"
  - "6.0"
  - "4.0"

notifications:
  email: false

script: xvfb-run ./script/cibuild

git:
  depth: 10

branches:
  only:
    - master
