version: "{build}"

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules

branches:
  only:
    - master

clone_depth: 10

skip_tags: true

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn test
  - yarn prebuild-node
  - yarn prebuild-node-ia32
  - yarn prebuild-electron
  - yarn prebuild-electron-ia32
  - yarn upload

test: off
deploy: off
